import assert from "node:assert/strict";
import { createServer } from "node:http";
import {
  createCipheriv, createDecipheriv, createPrivateKey, createPublicKey, diffieHellman,
  generateKeyPairSync, hkdfSync, randomBytes,
} from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { createContractService } from "../dist/agent-contract/service.js";
import { parseContractTokens, tokenAuthenticator, createContractHttpHandler } from "../dist/agent-contract/http-handler.js";

// N4b-8 gap 2 (DEMO-VERIFICATION-SCRIPT step 5): the N5 signer emits the
// LISTING-BOUND rendezvous seal {v:4, epk, iv, ct, tag} — the server must
// carry it opaque (it can never open it) and the provider's signer opens it
// under the listing's own id. v:2 remains only where CONTRACT_LEVEL=L.

const VECTORS = JSON.parse(readFileSync(
  path.join(path.dirname(fileURLToPath(import.meta.url)), "fixtures", "seal-v4-vectors.json"),
  "utf8",
));

// --- independent seal implementation (mirrors CONTRACT-PAYLOADS-v2 §Seal) --
// Same construction the vectors were generated by; if this decrypts the
// fixtures, the wire both sides implement is proven identical.

const EPK_BYTES = 32, IV_BYTES = 12, TAG_BYTES = 16;
const hex = (h) => Buffer.from(h.slice(2), "hex");
const lp = (s) => { const b = Buffer.from(s, "utf8"); return Buffer.concat([Buffer.from([b.length]), b]); };

function x25519Pub(rawHex) {
  return createPublicKey({ key: { kty: "OKP", crv: "X25519", x: hex(rawHex).toString("base64url") }, format: "jwk" });
}
function v4Context(epkRaw, recipientRaw, listingId) {
  return Buffer.concat([Buffer.from("agent-contract seal v1.1", "utf8"), epkRaw, recipientRaw, lp(listingId)]);
}

function openV4(privateJwk, recipientPubHex, box, listingId) {
  const privateKey = createPrivateKeyFromJwk(privateJwk);
  const epkRaw = hex(box.epk);
  const context = v4Context(epkRaw, hex(recipientPubHex), listingId);
  const key = Buffer.from(hkdfSync("sha256", diffieHellman({ privateKey, publicKey: x25519Pub(box.epk) }), Buffer.alloc(0), context, 32));
  const dec = createDecipheriv("aes-256-gcm", key, hex(box.iv), { authTagLength: TAG_BYTES });
  dec.setAAD(context);
  dec.setAuthTag(hex(box.tag));
  return Buffer.concat([dec.update(hex(box.ct)), dec.final()]).toString("utf8");
}

function createPrivateKeyFromJwk(jwk) {
  return createPrivateKey({ key: jwk, format: "jwk" });
}

// --- harness ----------------------------------------------------------------

const POLICY_DIGESTS = { buyer: `0x${"7".repeat(64)}`, provider: `0x${"8".repeat(64)}` };
const HOST_ROOTS = [];
const SIGNER = { keyId: "contract-server-test", privateKey: generateKeyPairSync("ed25519").privateKey };
const TOKENS = "tb1:buyer:kb1:9452:initiator,tp1:provider:kp1:9453:responder";

const ACCEPT = "application/json, text/event-stream";

async function boot(serviceOptions = {}) {
  const service = createContractService({
    hostRoots: HOST_ROOTS, signer: SIGNER, policyDigests: POLICY_DIGESTS, ...serviceOptions,
  });
  const handler = createContractHttpHandler({
    authenticate: tokenAuthenticator(parseContractTokens(TOKENS)),
    hostRoots: HOST_ROOTS, signer: SIGNER, service,
  });
  const srv = createServer(handler);
  await new Promise((r) => srv.listen(0, "127.0.0.1", r));
  const url = `http://127.0.0.1:${srv.address().port}`;
  const sessions = new Map();
  const rpc = async (token, name, args = {}) => {
    let sid = sessions.get(token);
    if (!sid) {
      const init = await fetch(`${url}/contract/mcp`, {
        method: "POST",
        headers: { "content-type": "application/json", accept: ACCEPT, authorization: `Bearer ${token}` },
        body: JSON.stringify({ jsonrpc: "2.0", id: 0, method: "initialize",
          params: { protocolVersion: "2025-03-26", capabilities: {}, clientInfo: { name: "t", version: "1" } } }),
      });
      sid = init.headers.get("mcp-session-id");
      sessions.set(token, sid);
      await fetch(`${url}/contract/mcp`, {
        method: "POST",
        headers: { "content-type": "application/json", accept: ACCEPT, authorization: `Bearer ${token}`, "mcp-session-id": sid },
        body: JSON.stringify({ jsonrpc: "2.0", method: "notifications/initialized" }),
      });
    }
    const res = await fetch(`${url}/contract/mcp`, {
      method: "POST",
      headers: { "content-type": "application/json", accept: ACCEPT, authorization: `Bearer ${token}`, "mcp-session-id": sid },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/call", params: { name, arguments: args } }),
    });
    const text = await res.text();
    const data = text.split("\n").find((l) => l.startsWith("data:"));
    const body = JSON.parse(data ? data.slice(5) : text);
    return { ...(body.result?.structuredContent ?? {}), ...(body.error ? { rpcError: body.error.code } : {}) };
  };
  return { service, rpc, close: () => { srv.close(); service.close(); } };
}

// --- tests ------------------------------------------------------------------

test("independent open decrypts every published v:4 vector under its listingId", () => {
  const recipientPriv = VECTORS.recipient.privateKeyJwk;
  const recipientPub = VECTORS.recipient.publicKeyHex;
  for (const v of VECTORS.vectors) {
    assert.equal(openV4(recipientPriv, recipientPub, v.box, v.listingId), v.plaintext);
  }
  // Wrong listingId must NOT open — the binding is real.
  assert.throws(() => openV4(recipientPriv, recipientPub, VECTORS.vectors[0].box, "lst-other"));
});

test("v:4 sealed invitation round-trips byte-identical and opens under the listingId", async () => {
  const env = await boot(); // no allowLegacySealV2 — the S/P posture
  try {
    const listing = await env.rpc("tp1", "rendezvous_publish_listing", {
      title: "SFO-FCO managed", summary: "desk",
      sealedBoxPublicKeyHex: VECTORS.recipient.publicKeyHex,
    });
    assert.match(listing.listingId, /^lst-/);
    // Seal a fresh v:4 box to the listing's key bound to ITS listingId —
    // what the buyer's N5 signer does in the demo.
    const ephemeral = generateKeyPairSync("x25519");
    const epkRaw = Buffer.from(ephemeral.publicKey.export({ format: "jwk" }).x, "base64url");
    const context = v4Context(epkRaw, hex(VECTORS.recipient.publicKeyHex), listing.listingId);
    const key = Buffer.from(hkdfSync("sha256", diffieHellman({
      privateKey: ephemeral.privateKey, publicKey: x25519Pub(VECTORS.recipient.publicKeyHex),
    }), Buffer.alloc(0), context, 32));
    const iv = randomBytes(IV_BYTES);
    const cipher = createCipheriv("aes-256-gcm", key, iv, { authTagLength: TAG_BYTES });
    cipher.setAAD(context);
    const ct = Buffer.concat([cipher.update("meet at gate 7, 14:00"), cipher.final()]);
    const box = {
      v: 4,
      epk: `0x${epkRaw.toString("hex")}`,
      iv: `0x${iv.toString("hex")}`,
      ct: `0x${ct.toString("hex")}`,
      tag: `0x${cipher.getAuthTag().toString("hex")}`,
    };
    const sent = await env.rpc("tb1", "rendezvous_send_invitation", {
      listingId: listing.listingId, sealedInvitation: box,
    });
    assert.equal(sent.delivered, true);
    // Inbox returns the byte-identical box — the server never touched it.
    const inbox = await env.rpc("tp1", "rendezvous_inbox", {});
    const msg = inbox.messages.find((m) => m.listingId === listing.listingId);
    assert.deepEqual(msg.sealedPayload, box);
    // ... and the provider opens it under its configured listing id.
    assert.equal(
      openV4(VECTORS.recipient.privateKeyJwk, VECTORS.recipient.publicKeyHex, msg.sealedPayload, listing.listingId),
      "meet at gate 7, 14:00",
    );
    // A published fixture box also delivers opaque (listingId binding is the
    // signer's job — the wire is identical).
    const fixtureBox = VECTORS.vectors[0].box;
    const sentFixture = await env.rpc("tb1", "rendezvous_send_invitation", {
      listingId: listing.listingId, sealedInvitation: fixtureBox,
    });
    assert.equal(sentFixture.delivered, true);
  } finally { env.close(); }
});

test("v:2 is refused at S/P posture and accepted at L", async () => {
  const v2 = VECTORS.legacyV2.box;
  const strict = await boot(); // default: no legacy v2 — what S/P config yields
  try {
    const listing = await strict.rpc("tp1", "rendezvous_publish_listing", {
      title: "legacy check", summary: "s", sealedBoxPublicKeyHex: VECTORS.recipient.publicKeyHex,
    });
    const refused = await strict.rpc("tb1", "rendezvous_send_invitation", {
      listingId: listing.listingId, sealedInvitation: v2,
    });
    assert.equal(refused.error, "PAYLOAD_INVALID");
  } finally { strict.close(); }

  const lax = await boot({ allowLegacySealV2: true });
  try {
    const listing = await lax.rpc("tp1", "rendezvous_publish_listing", {
      title: "legacy check", summary: "s", sealedBoxPublicKeyHex: VECTORS.recipient.publicKeyHex,
    });
    const ok = await lax.rpc("tb1", "rendezvous_send_invitation", {
      listingId: listing.listingId, sealedInvitation: v2,
    });
    assert.equal(ok.delivered, true);
  } finally { lax.close(); }
});

test("CONTRACT_LEVEL gates v:2 via loadContractConfig", async () => {
  // The service option is wired from level: L → legacy allowed, S/P → refused.
  const { loadContractConfig } = await import("../dist/agent-contract/config.js");
  const base = {
    CONTRACT_MCP_ENABLED: "1",
    CONTRACT_AUTH_TOKENS: TOKENS,
    CONTRACT_SERVER_ED25519_SEED: Buffer.alloc(32, 7).toString("base64"),
    CONTRACT_SERVER_KEY_ID: "contract-server-test",
    CONTRACT_SERVER_KEY_VALID_FROM: "2020-01-01T00:00:00Z",
    CONTRACT_POLICY_DIGESTS: `buyer:${POLICY_DIGESTS.buyer},provider:${POLICY_DIGESTS.provider}`,
    CONTRACT_STATE_DIR: "/tmp/n4b8-seal-level-check",
  };
  // L boots without the statement gate and allows v2; S refuses startup
  // without CONTRACT_REQUIRE_BIND_STATEMENT=1 (existing rule) — assert the
  // allowLegacySealV2 derivation on a bootable S config.
  const l = loadContractConfig({ ...base, CONTRACT_STATE_DIR: "/tmp/n4b8-seal-level-L" });
  assert.equal(l.kind, "ready");
  const s = loadContractConfig({
    ...base, CONTRACT_STATE_DIR: "/tmp/n4b8-seal-level-S",
    CONTRACT_LEVEL: "S", CONTRACT_REQUIRE_BIND_STATEMENT: "1",
    TELEMETRY_CLOSE_URL: "http://telemetry-sink:8083",
  });
  assert.equal(s.kind, "ready");
  // The behavior difference is exercised by the dispatch tests above; here we
  // only assert the config-level wiring exists by constructing both services.
  assert.ok(l.service);
  assert.ok(s.service);
  l.service.close();
  s.service.close();
});
